### PR TITLE
Add Builder to DefaultStateMachineContext with pojobuilder #526

### PR DESCRIPTION
**Pull request by alexandrenavarro**

### CODE REVIEW

**Comment by jvalkeal** [comment]
Unfortunately we can't and don't want to start using code generation. It creates more problems that it's realistically going to resolve. Also you end up with IDE issues and possible build issues in a future when tooling lacks possible gradle versions we'd like to use.

**Comment by jvalkeal** [comment]
I pretty much feel same what went through in ambari forums when they wanted to add freebuilder http://mail-archives.apache.org/mod_mbox/ambari-dev/201803.mbox/%3CF33EF054-397B-4DE8-8C07-887DAAA04C2B%40hortonworks.com%3E

**Comment by alexandrenavarro** [comment]
OK, are you ok at least to add a builder in source code for DefaultStateMachineContext (see question un #526)?

**Comment by jvalkeal** [comment]
Yes, builder pattern itself is fine.

**Comment by jvalkeal** [comment]
closing this in favour of doing these manually where needed.

**Pull request closed without merging**
