### PR TITLE
Upgrade to Spring Boot 3

### PR DESCRIPTION
**Pull request by egreijus**
This upgrades the project to Spring Boot 3 (3.1.1) and JDK 17 so that Spring State Machine can be used in projects based on Spring Boot 3.

(A CLA has been completed)

### CODE REVIEW

**Comment by kjberglund** [comment]
This would be great to have, what do you think @jvalkeal ?

**Comment by gustavodaquino** [comment]
I agree with the migration proposal to Spring Boot 3.0 for compliance reasons.

**Comment by noaHson86** [comment]
how is it going? would like to move projects to spring 3.
appreciate your hard work.

**Comment by mrjovanovicns** [comment]
Is there any progress on this? We are also looking to use this in our spring 3 java 17 project.

**Comment by varuntayur** [comment]
Any update on this please

**Comment by andreas-schilling** [comment]
Would be great to have this to be able to perform a migration of our application to Spring Boot 3 ❤️

**Comment by relyativus** [comment]
Hey guys. I am waiting for this as well. Any estimation on when this will be released? Thanks a lot for your effort!

**Comment by egreijus** [comment]
All, thanks for the encouraging comments.
I'd be more than happy to receive comments and suggestions on enhancements in order to have this merged and finally built.

**Review by serhan-iskander — APPROVED** [review]

**Comment by SachinSharmaa** [comment]
@jvalkeal  Can we please have a timeline here? If there is a plan to release a spring boot 3 compatible version or not?
We are planning on using Spring State Machine, but we are reluctant on working with spring boot 2 in new service.

**Comment by jvalkeal** [comment]
Thanks a lot for the PR as it's a good start for boot 3 upgrade. I will polish it a bit before merging.

**Comment by Steve973** [comment]
It looks like nobody tested this with AOT processing.  As of SB 3.2.0 and StateMachine 4.0.0, this still causes an error described in https://github.com/spring-projects/spring-statemachine/issues/1080

**Comment by olwe12** [comment]
Unfortunately it's just as @Steve973 wrote, it still doesn't work

**Pull request merged**
