### PR TITLE
Use the contextObj as is when saving the StateMachineContext

### LINKED ISSUE #494: RepositoryStateMachinePersist not using contextObj as id
When saving a state machine with e.g. the `MongoDbRepositoryStateMachinePersist` implementation, the contextObj that is passed to the `write` method in `RepositoryStateMachinePersist` is not used at all instead of being set as the primary key or (or mongo ObjectId in this case). A default mongo objectId is therefore created and the state machine cannot be found when reading it with the `read` method (which is doing a `getRepository().findById(contextObj.toString())`).

The redis and mongo implementations use a separate field for the `@Id`, whereas the JPA impl uses the machineId as the primary key (which seems wrong).

### PR DESCRIPTION
**Pull request by ractive**
Fixes #494

I did not change the `JpaRepositoryStateMachine` although I think there should be a separate `@Id` field as well, which should be set to contextObj also.

### CODE REVIEW

**Comment by ractive** [comment]
I'd like to see this backported to at least the 1.2.x branch.

**Comment by jvalkeal** [comment]
@ractive It'd be nice if we'd have a test to verify issues with current code base. There's some integration tests which are skipped if local mongo is not available. We clearly miss test coverage with this issue.

**Comment by jvalkeal** [comment]
@ractive If I don't hear back from you soon, I'll try to create some tests myself to verify this pr.

**Comment by jvalkeal** [comment]
Merged with some changes per 041189bb31521dc9fc4d614d37cd20e42a243af3

**Pull request closed without merging**
