### PR TITLE
Fix broken JIRA link in contribution guidelines

### PR DESCRIPTION
**Pull request by mprimi**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mprimi Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-statemachine&pullRequestId=492)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-statemachine&pullRequestId=492) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@mprimi Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-statemachine&pullRequestId=492)!

**Comment by jvalkeal** [comment]
yeah thanks, leftover when copied over.

**Comment by jvalkeal** [comment]
Merged per https://github.com/spring-projects/spring-statemachine/commit/c693e79f124c744631a8b8eef29d8450c28dcbb4

**Pull request closed without merging**
