### PR TITLE
Fixed issue: 588

### PR DESCRIPTION
**Pull request by AdarWesley**
https://github.com/spring-projects/spring-statemachine/issues/588
Added relevant test case.
Refactored actions loading code to eliminate duplicated code.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@AdarWesley Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-statemachine&pullRequestId=804)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-statemachine&pullRequestId=804) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@AdarWesley Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-statemachine&pullRequestId=804)!

**Comment by jvalkeal** [comment]
Thanks for a PR and sorry taking so long. Think looks good and will merge shortly!

**Comment by jvalkeal** [comment]
Merged per a8a842fc2aaff92ef25311c002ea9ac31e760ca7 and just polished commit message.

**Pull request closed without merging**
