### PR TITLE
Add getters on some fields in TimeTrigger

### PR DESCRIPTION
**Pull request by alexandrenavarro**
Add getters on some fields in TimeTrigger.

As you add some getter on Transition recently, I would like to add some getters on TimeTrigger.
In my project, we generate automatically some graph image via PlantUML from the configuration of the state machine and we want to see on these information (timeout / count).

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@alexandrenavarro Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-statemachine&pullRequestId=532)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-statemachine&pullRequestId=532) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@alexandrenavarro Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-statemachine&pullRequestId=532)!

**Comment by alexandrenavarro** [comment]
Made a mistake with my branches, I will close the Pull request and recreate another one.

**Comment by jvalkeal** [comment]
@alexandrenavarro yeah, you should ever commit anything into your own clone master branch as things go south after that. Always use a branch which allows you to update your own master from upstream.

**Pull request closed without merging**
