### PR TITLE
Update to latest versions of dependencies, renamed EnsembleListeger

### PR DESCRIPTION
**Pull request by mjkrumlauf**
Several dependencies were updated to their latest versions, and EnsembleListeger was renamed to EnsembleListener (I assumed since the implementations of EnsembleListeger were listeners...)

### CODE REVIEW

**Comment by jvalkeal** [comment]
Thanks for catching that typo in a listener name. Think versions are also ok because it'd align with platform 2.x where state machine eventually goes. Though kryo is 3.0.3 in platform 2.x.

**Comment by jvalkeal** [comment]
@mjkrumlauf I think you forgot to add `EnsembleListener` back to git when you renamed it. It's not part of this PR so compile fails.

**Comment by mjkrumlauf** [comment]
Sorry about missing file.  It's added now.

**Comment by jvalkeal** [comment]
I'm just doing a little housekeeping on versions used in samples. Boot still depends on older framework libs so I need to define some versions manually until boot 1.3.x is released.

**Pull request merged**
