### PR TITLE
Support WithStateMachine annotation with state machine generated by StateMachineFactory when id is empty or dynamically generated

### PR DESCRIPTION
**Pull request by gvagenas**
**Issue https://github.com/spring-projects/spring-statemachine/issues/940**

When using StateMachineFactory generated state machine with either empty id or a dynamically generated id its not possible to use `@WithStateMachine` anno:

- `factory.getStateMachine();` -> `name` property of the state machine will be null
- `factory.getStateMachine(myDynamicGeneratedID);` -> `id` will be set to `myDynamicGeneratedID` but cannot be used with `@WithStateMachine` but the id is not know before runtime.

The provided PR fixes the following:

- `factory.getStateMachine();` -> `name` will result to default `org.springframework.statemachine.StateMachineSystemConstants#DEFAULT_ID_STATEMACHINE`
- Any bean with `@WithStateMachine` or `@WithStateMachine(id = StateMachineSystemConstants.DEFAULT_ID_STATEMACHINE)` will be attached to the state machines generated by factory

**CLA submitted**

### CODE REVIEW

**Comment by gvagenas** [comment]
In the `Smoke/build` check the test `org.springframework.statemachine.buildtests.TimerSmokeTests` failed, but locally is passing, is that a known unstable test?

**Comment by jvalkeal** [comment]
Sorry for delay looking this PR. Yes, `TimerSmokeTests` has been flaky.

**Comment by jvalkeal** [comment]
I think this is fairly good workaround for this issue. Thanks for PR! lgtm

**Comment by jvalkeal** [comment]
merged per 043d2a75314e879a83f9a32b760d19f5808c66f9

**Comment by gvagenas** [comment]
Great, thanks for review and merging @jvalkeal

**Pull request closed without merging**
